 name: Check secrets presence (no leak)
  run: |
    if [ -z "${{ secrets.BLOCKVISION_API_KEY }}" ]; then
      echo "BLOCKVISION_API_KEY is MISSING"; exit 1;
    else
      echo "BLOCKVISION_API_KEY is set ✅";
    fi
