
name: Sui portfolio daily snapshot (plaintext public)

on:
  schedule:
    - cron: '5 17 * * *'   # ~00:05 Asia/Bangkok (UTC+7)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run script
        env:
          SUI_ADDRESS: 0x9e10f69f6475bcb01fb2117facd665c68483da2cdefa6a681fa6a874af0df165
          SUI_RPC_URL: https://fullnode.mainnet.sui.io:443
          OUT_DIR: data
        run: |
          python scripts/sui_daily_portfolio.py
      - name: Commit snapshot
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add -A data
          git commit -m "chore: daily snapshot" || echo "no changes"
          git push
